#!/bin/bash

if [ $# != 2 ]; then
	echo "Usage: transfer_example example_new example_old"
	exit 1
fi

if [ -f "$1/script" ]; then
	./ego -t "$1/script" "$1/config.txt" "$1/transfer.csv" "$2/output.csv"
	exit 0
fi

if [ -f "$1/script.py" ]; then
	./ego -t "python3 $1/script.py" "$1/config.txt" "$1/transfer.csv" "$2/output.csv"
	exit 0
fi

if [ -f "$1/results.csv" ]; then
	./ego -t "python3 scripts/lookup.py $1/results.csv" "$1/config.txt" "$1/transfer.csv" "$2/output.csv"
	exit 0
fi

echo "No script provided"
exit 1
